[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "push"
authors = [{name = "Daniel Huange", email = "danielhuange@sfsu.edu"}]
dynamic = ["version", "description"]
